# Site settings
name: Shark
email: sha4yu0119@gmail.com
author: Freud Kang
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/shark0119/
baseurl: ""
description: Find Yourself
meta_description: Find Yourself
motto: Falling down from the TRUMP building
banner: Find Yourself

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: shark0119

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

